apiVersion: networking.k8s.io/v1beta1
kind: Ingress
metadata:
  namespace: jenkins
  name: frontend-portal-ingress
  labels:
    env: production
    tier: frontend
    app: portal
    name: frontend-portal-ingress
spec:
  rules:
    - host: portal.192.168.100.66.nip.io # TODO
      http:
        paths:
          - path: /
            backend:
              serviceName: frontend-portal
              servicePort: 3000